# Imports

In [32]:
import pandas as pd

# 1. Leitura dos dados

In [82]:
data = pd.read_csv('dataset\\RECLAMEAQUI_PAODEACUCAR.csv')

data

,ID,TEMA,LOCAL,TEMPO,CATEGORIA,STATUS,DESCRICAO,URL,ANO,MES,DIA,DIA_DO_ANO,SEMANA_DO_ANO,DIA_DA_SEMANA,TRIMETRES,CASOS
0,147765939,Preço na prateleira diferente do que está no c...,Campinas - SP,2022-01-08,Pão de Açúcar<->Supermercados<->Propaganda eng...,Resolvido,Alegando erro operacional mas que se repete se...,https://www.reclameaqui.com.br//pao-de-acucar/...,2022,1,8,8,1,5,1,24
1,147699053,UTILIZAÇÃO INDEVIDA DOS MEUS STIX,São Paulo - SP,2022-01-08,Clubes de Compras e Vantagens<->Pão de Açúcar<...,Resolvido,Estou chocada pois acabei de ver um e-mail na ...,https://www.reclameaqui.com.br//pao-de-acucar/...,2022,1,8,8,1,5,1,24
2,147700991,Não recebi meu estorno,Rio de Janeiro - RJ,2022-01-08,Supermercados<->Não encontrei meu problema<->P...,Respondida,"Fiz um reclamação semana passada, devido uma c...",https://www.reclameaqui.com.br//pao-de-acucar/...,2022,1,8,8,1,5,1,24
3,147703729,Tiraram pontos stix da conta.,São Paulo - SP,2022-01-08,Clubes de Compras e Vantagens<->Pão de Açúcar<...,Respondida,Conclui minha a meta gasto mensal no programa ...,https://www.reclameaqui.com.br//pao-de-acucar/...,2022,1,8,8,1,5,1,24
4,147705769,[Editado pelo Reclame Aqui] pontos stix,São Paulo - SP,2022-01-08,Clubes de Compras e Vantagens<->Pão de Açúcar<...,Respondida,Pela segunda vez no mesmo mês tive meus pontos...,https://www.reclameaqui.com.br//pao-de-acucar/...,2022,1,8,8,1,5,1,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,150028525,Não entregam nunca no horário limite,São Paulo - SP,2022-12-09,Atraso na entrega<->Supermercados<->Pão de Açúcar,Respondida,"Sempre que peço no site do pão de açúcar, agen...",https://www.reclameaqui.com.br//pao-de-acucar/...,2022,12,9,343,49,4,4,18
996,150029021,Pão de Açúcar e a dívida que desconheço.,São Paulo - SP,2022-12-09,Pão de Açúcar<->Não encontrei meu problema<->C...,Não respondida,"A empresa ITAPEVA, tem negativado meu nome com...",https://www.reclameaqui.com.br//pao-de-acucar/...,2022,12,9,343,49,4,4,18
997,150029875,Desconto 20% em Vinhos não concedido,Rio Negrinho - SC,2022-12-09,Pão de Açúcar<->Divergência de valores<->Bebidas,Não respondida,No dia 22/08/2022 realizei uma compra de vinho...,https://www.reclameaqui.com.br//pao-de-acucar/...,2022,12,9,343,49,4,4,18
998,149991011,itens faltantes,São Paulo - SP,2022-12-09,Pão de Açúcar<->Hipermercados<->Entrega faltan...,Não respondida,Fiz uma compra no site do pão de açucar e veio...,https://www.reclameaqui.com.br//pao-de-acucar/...,2022,12,9,343,49,4,4,18
999,150027043,Pizza de Mussarela Estragada,São Paulo - SP,2022-12-09,Pão de Açúcar<->Não encontrei meu problema<->E...,Não respondida,No dia 09/09/22 comprei uma pizza de mussarela...,https://www.reclameaqui.com.br//pao-de-acucar/...,2022,12,9,343,49,4,4,18

# 2. Análise estrutural do dataset

In [83]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             1000 non-null   int64
 1   TEMA           1000 non-null   str
 2   LOCAL          1000 non-null   str
 3   TEMPO          1000 non-null   str
 4   CATEGORIA      1000 non-null   str
 5   STATUS         1000 non-null   str
 6   DESCRICAO      1000 non-null   str
 7   URL            1000 non-null   str
 8   ANO            1000 non-null   int64
 9   MES            1000 non-null   int64
 10  DIA            1000 non-null   int64
 11  DIA_DO_ANO     1000 non-null   int64
 12  SEMANA_DO_ANO  1000 non-null   int64
 13  DIA_DA_SEMANA  1000 non-null   int64
 14  TRIMETRES      1000 non-null   int64
 15  CASOS          1000 non-null   int64
dtypes: int64(9), str(7)
memory usage: 125.1 KB

In [ ]:
# Transformar todos os nomes das colunas em letras minúsculas
data.columns = data.columns.str.lower()

data.columns.tolist()

In [86]:
# Primeira visão de variáveis categóricas chave. Contagem de valores únicos
print(f"~> Número de temas únicos: {data['tema'].nunique()}")
print(f"~> Número de locais únicos: {data['local'].nunique()}")
print(f"~> Número de datas únicas: {data['tempo'].nunique()}")
print(f"~> Número de categorias únicas: {data['categoria'].nunique()}")
print(f"~> Número de descrições únicas: {data['descricao'].nunique()}")
print(f"~> Padrões de status únicos: {data['status'].unique().tolist()}")

~> Número de temas únicos: 944
~> Número de locais únicos: 135
~> Número de datas únicas: 71
~> Número de categorias únicas: 210
~> Número de descrições únicas: 989
~> Padrões de status únicos: ['Resolvido', 'Respondida', 'Em réplica', 'Não respondida', 'Não resolvido']

# 3. Análise Exploratória de Dados

In [67]:
# Realizar a verificação se há alguma coluna com pelo menos um valor nulo.
print('_' * 42)
print(f'|{'Valores nulos por coluna': ^40}|')
print('-' * 42)

for i in data.columns:
    print(f'|{i: <20}',end='')
    print(f'{data[i].isna().sum(): >20}|')
    
print('-' * 42)

__________________________________________
|        Valores nulos por coluna        |
------------------------------------------
|ID                                     0|
|TEMA                                   0|
|LOCAL                                  0|
|TEMPO                                  0|
|CATEGORIA                              0|
|STATUS                                 0|
|DESCRICAO                              0|
|URL                                    0|
|ANO                                    0|
|MES                                    0|
|DIA                                    0|
|DIA_DO_ANO                             0|
|SEMANA_DO_ANO                          0|
|DIA_DA_SEMANA                          0|
|TRIMETRES                              0|
|CASOS                                  0|
------------------------------------------

In [ ]:
print('_' * 110)
print(f'|{'Valores nulos por coluna': ^78}|')
print('-' * 110)
data.describe().T

____________________________________________________________________________________________________
|                           Valores nulos por coluna                           |
----------------------------------------------------------------------------------------------------

,count,mean,std,min,25%,50%,75%,max
id,1000.0,1.485025e+08,1.139302e+06,146345143.0,147598303.5,148473420.0,149516314.5,150438193.0
ano,1000.0,2.022000e+03,0.000000e+00,2022.0,2022.0,2022.0,2022.0,2022.0
mes,1000.0,7.272000e+00,2.506052e+00,1.0,7.0,8.0,8.0,12.0
dia,1000.0,1.551700e+01,7.397461e+00,7.0,9.0,14.0,21.0,31.0
dia_do_ano,1000.0,2.053620e+02,7.769883e+01,8.0,194.0,221.0,243.0,343.0
semana_do_ano,1000.0,2.950700e+01,1.113759e+01,1.0,28.0,32.0,35.0,49.0
dia_da_semana,1000.0,2.813000e+00,1.864808e+00,0.0,1.0,3.0,4.0,6.0
trimetres,1000.0,2.786000e+00,7.891938e-01,1.0,3.0,3.0,3.0,4.0
casos,1000.0,1.663000e+01,5.821597e+00,2.0,14.0,17.0,21.0,33.0

In [75]:
data.nunique()

id                996
tema              944
local             135
tempo              71
categoria         210
status              5
descricao         989
url              1000
ano                 1
mes                12
dia                22
dia_do_ano         71
semana_do_ano      21
dia_da_semana       7
trimetres           4
casos              25
dtype: int64